[package]
name = "vn_poker_llm"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.93"
bevy = { version = "0.14", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_pbr",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "default_font",
    "hdr",
    "jpeg",
    "multi_threaded",
    "png",
    "smaa_luts",
    "sysinfo_plugin",
    "tonemapping_luts",
    "webgl2",
    "x11",
] }
bevy_la_mesa = { path="../bevy_la_mesa" }
bevy_lunex = { version = "0.2.4" }
bevy_novel = { path="../bevy_novel"}
bevy-inspector-egui = "0.27.0"
bevy-tokio-tasks = "=0.14.0"
image = "0.25.5"
pecs = { git="https://github.com/stillonearth/pecs.git", rev ="97879f3" }
rand = "0.8"
renpy_parser = "0.0.6"
serde = "1.0.215"
serde_json = "1.0.133"
url = "2.5.3"
reqwest = "0.12.9"

[dependencies.uuid]
version = "1.11.0"
features = [
    "v4",
    "fast-rng",
]

